### ISSUE TITLE
reverse primers and lowercase letters

### ISSUE THREAD

**Issue by Josh-Lefler** [jsh58/FlowClus#2]
Hello,

When I provide the oligos txt file with my reverse primer and request that it remove those sequences that do not have the reverse primer, it seems that FlowClus does not count those sequences in which the reverser primer is present, but either some or all of the bases are lowercase (which I assume means a low quality score?) Is there a way to circumvent this or have FlowClus ignore case?

Thanks

**Comment by jsh58** [comment]
Josh,

Thanks for your question.  FlowClus does consider case in the primer matching.  Is there a reason why you want to keep lowercase bases in your sequences?  If not, you should convert them to uppercase using `tr` or `sed`.

John Gaspar
